services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: ftr-pos-web
    restart: always
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_API_URL=http://api:3000